### ISSUE TITLE
Add a CONTRIBUTE.md document

### ISSUE THREAD

**Issue by RichardLitt** [ben-aaron188/netanos#3]
Currently, I don't know if I can contribute to this code at all. Are you interested in long term maintenance? 

A Code of Conduct would also be good. 

Related to https://github.com/openjournals/joss-reviews/issues/283#issuecomment-307141013.

**Comment by ben-aaron188** [comment]
Thanks for pointing us to the CoC and contributing guidelines. We've added both.
