### ISSUE TITLE
Add DOIs to references in paper.md

### ISSUE THREAD

**Issue by RichardLitt** [ben-aaron188/netanos#4]
In https://github.com/ben-aaron188/netanos/blob/master/paper/paper.md, you have some references. Each should have a DOI to point to, as well. If there aren't any, state that here and close this. 

Related to https://github.com/openjournals/joss-reviews/issues/293.

**Comment by ben-aaron188** [comment]
We added the DOIs where they were available. For "NLP compromise",  "ner" and the UK Data Archive anonymization guideline, there weren't any.
